PharmacySystem/AdminLTE Template1/Controllers/MedicinesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AdminLTE_Template1.Models;
using PagedList;
using System.IO;

namespace AdminLTE_Template1.Controllers
{
    public class MedicinesController : Controller
    {
        private PharmacySystemEntities db = new PharmacySystemEntities();

        public ActionResult Index(string option, string search, int? pageNumber)
        {
            var totMedicineCount = db.MedicineDetails.Count();
            ViewData["TotalMedicines"] = totMedicineCount;
            //if a user choose the radio button option as Subject  
            if (option == "MedicineName")
            {
                //if (String.IsNullOrEmpty(search))
                //{
                //    ViewBag. EmptySearchID = 1;
                //    ViewData["ErrorMessage"] = "pls enter the word to search";
                //    return View(db.MedicineDetails.Where(x => x.MedicineName.Contains(search) || search == null).ToList().ToPagedList(pageNumber ?? 1, 9));
                // }
                return View(db.MedicineDetails.Where(x => x.MedicineName.Contains(search) || search == null).ToList().ToPagedList(pageNumber ?? 1, 9));
            }

            else
            {

                //if (String.IsNullOrEmpty(search))
                //{
                //    ViewBag.EmptySearchID = 1;
                //    ViewData["ErrorMessage"] = "pls enter the word to search";
                //    return View();
                //}
                return View(db.MedicineDetails.Where(x => x.CategoryDisease.CategoryName.Contains(search) || search == null).ToList().ToPagedList(pageNumber ?? 1, 9));
            }
        }

        // GET: Medicines/Details/5
        public ActionResult Details(short? id)
        {
            if (id == null)
            {
                ViewData["Exception"] = "Datas are Not Exists";
                return View("CommonError");
            }
            MedicineDetail medicineDetail = db.MedicineDetails.Find(id);
            if (medicineDetail == null)
            {
                ViewData["Exception"] = "Datas are Not Exist";
                return View("CommonError");
            }
            return View(medicineDetail);
        }

        // GET: Medicines/Create
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.CategoryDiseases, "C_ID", "CategoryName");
            return View();
        }

        // POST: Medicines/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MedicineDetail medicineDetail, HttpPostedFileBase file)
        {
            try
            {
                //if (ModelState.IsValid)
                //{
                if (file != null)
                {
                    string pic = System.IO.Path.GetFileName(file.FileName);
                    string savePath = Server.MapPath("~/Content/img/");
                    //string path = System.IO.Path.Combine(Server.MapPath( pic));
                    // file is uploaded
                    MedicineDetail s = new MedicineDetail();

                    s.ManufacturedDate = medicineDetail.ManufacturedDate;
                    s.ExpiredDate = medicineDetail.ExpiredDate;
                    s.Dosage = medicineDetail.Dosage;
                    s.MedicineName = medicineDetail.MedicineName;
                    s.CategoryID = medicineDetail.CategoryID;
                    s.Price = medicineDetail.Price;
                    s.Description = medicineDetail.Description;
                    s.Quantity = medicineDetail.Quantity;
                    s.AddMonth = DateTime.Now.ToString("MMMM");

                    s.Image = pic;
                    file.SaveAs(Path.Combine(savePath, pic));
                    //file.SaveAs(pic);
                    db.MedicineDetails.Add(s);
                    try
                    {
                        db.SaveChanges();
                    }
                    catch (Exception)
                    {
                        return View();
                    }


                    return RedirectToAction("Index");
                }
                // }

                ViewBag.CategoryID = new SelectList(db.CategoryDiseases, "C_ID", "CategoryName", medicineDetail.CategoryID);
                return View(medicineDetail);
            }
            catch (Exception)
            {

                ViewData["Exception"] = "Cant Create";
                //return View("CommonError");
            }
            ViewBag.CategoryID = new SelectList(db.CategoryDiseases, "C_ID", "CategoryName", medicineDetail.CategoryID);
            return View(medicineDetail);
        }

        // GET: Medicines/Edit/5
        public ActionResult Edit(short? id)
        {
            if (id == null)
            {
                ViewData["Exception"] = "Datas are Not Exists";
                return View("CommonError");
            }
            MedicineDetail medicineDetail = db.MedicineDetails.Find(id);
            if (medicineDetail == null)
            {
                ViewData["Exception"] = "Datas are Not Exists";
                return View("CommonError");
            }
            ViewBag.CategoryID = new SelectList(db.CategoryDiseases, "C_ID", "CategoryName", medicineDetail.CategoryID);
            return View(medicineDetail);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "M_ID,ManufacturedDate,ExpiredDate,Dosage,Image,MedicineName,CategoryID,Price,Description,Quantity")] MedicineDetail medicineDetail)
        {
            if (medicineDetail == null)
            {
                ViewData["Exception"] = "Datas are Not Exists";
                return View("CommonError");
            }

            if (ModelState.IsValid)
            {
                db.Entry(medicineDetail).State = EntityState.Modified;
                try
                {
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    ViewData["Exception"] = "Cant Update";
                    //return View("CommonError");
                }

            }
            ViewBag.CategoryID = new SelectList(db.CategoryDiseases, "C_ID", "CategoryName", medicineDetail.CategoryID);
            return View(medicineDetail);
        }
        // GET: Medicines/Delete/5
        public ActionResult Delete(short? id)
        {
            if (id == null)
            {
                ViewData["Exception"] = "Datas are Not Exists";
                return View("CommonError");
            }
            MedicineDetail medicineDetail = db.MedicineDetails.Find(id);
            if (medicineDetail == null)
            {
                ViewData["Exception"] = "Datas are Not Exists";
                //return View("CommonError");
            }
            return View(medicineDetail);
        }

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(MedicineDetail medicineDetail)
        //{
        //    if (medicineDetail == null)
        //    {
        //        ViewData["Exception"] = "Datas are Not Exists";
        //        return View("CommonError");
        //    }

        //    MedicineDetail s = new MedicineDetail();
        //    s.Image = medicineDetail.Image;
        //    s.ManufacturedDate = medicineDetail.ManufacturedDate;
        //    s.ExpiredDate = medicineDetail.ExpiredDate;
        //    s.Dosage = medicineDetail.Dosage;
        //    s.MedicineName = medicineDetail.MedicineName;
        //    s.Description = medicineDetail.Description;
        //    s.Price = medicineDetail.Price;
        //    s.Quantity = medicineDetail.Quantity;
        //    s.CategoryID = medicineDetail.CategoryID;
        //    db.MedicineDetails.Add(s);
        //    try
        //    {
        //        db.SaveChanges();
        //    }
        //    catch (Exception)
        //    {
        //        ViewData["Exception"] = "Cant Update";
        //        return View("CommonError");
        //    }

        //    // after successfully uploading redirect the user
        //    return RedirectToAction("Index", "Home");
        //}

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(short id)
        {
            MedicineDetail medicineDetail = db.MedicineDetails.Find(id);
            try
            {

                db.MedicineDetails.Remove(medicineDetail);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                ViewData["Exception"] = "Cant deleted";
                return View("CommonError");

            }
        }

        public ActionResult DateExpaired()
        {
            var list = db.MedicineDetails.SqlQuery("select * from dbo.MedicineDetails where GETDATE() > ExpiredDate").ToList();
            return View(list);
        }

        public ActionResult MedicineSort()
        {
            var list = db.MedicineDetails.SqlQuery("select * from dbo.MedicineDetails where GETDATE() < ExpiredDate order by ExpiredDate ASC").ToList();
            return View(list);
        }


        public ActionResult DateToBeExpaired()
        {
            var list = db.MedicineDetails.SqlQuery(" SELECT* FROM dbo.MedicineDetails WHERE ExpiredDate BETWEEN GETDATE()  AND DATEADD(day,30,GETDATE())").ToList();
            return View(list);
        }



        [HttpPost]
        public JsonResult DeleteInPopup(int m_ID)
        {

PharmacySystem/AdminLTE Template1/Views/Medicines/Create.cshtml
@model AdminLTE_Template1.Models.MedicineDetail
<h2 class="bg-danger" style="text-align:center;color:red">@ViewData["Exception"]</h2>
@using (Html.BeginForm("create", "medicines", FormMethod.Post,
                                                   new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4 style="color:brown;text-align:center"><b>Add New Medicine Detail</b></h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.MedicineName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MedicineName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MedicineName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ManufacturedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input name="ManufacturedDate" min="2017-01-01" type="date">
            </div>
            @Html.ValidationMessageFor(model => model.ManufacturedDate, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpiredDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input name="ExpiredDate" min="2017-03-25" type="date">
            </div>
            @Html.ValidationMessageFor(model => model.ExpiredDate, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Dosage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Dosage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Dosage, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Image,  new { @class = "form-control",@readonly=true, @Value = "~/content/img/medi2.jpg" })
                    @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            <label class="col-md-2 control-label">Select File : </label>
            <div class="col-md-10">
                @Html.TextBox("file", null, new { type = "file", @class = "form-control", placeholder = "Enter Address", accept = "image/x-png, image/gif, image/jpeg" })
                @Html.ValidationMessage("FileErrorMessage")
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, "CategoryID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
                <input class="btn btn-primary" type="reset" value="Reset">
            </div>
        </div>
    </div>
}

@*<div class="btn btn-info">
        @Html.ActionLink("Back to List", "Index")
    </div>*@

@*@section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }*@



<style>
    /* Full-width input fields */
    input[type=text], input[type=password] {
        width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        box-sizing: border-box;
    }

    /* Set a style for all buttons */
    button {
        background-color: #4CAF50;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        cursor: pointer;
        width: 100%;
    }

        button:hover {
            opacity: 0.8;
        }

    /* Extra styles for the cancel button */
    .cancelbtn {
        width: auto;
        padding: 10px 18px;
        background-color: #f44336;
    }

    /* Center the image and position the close button */
    /*.imgcontainer {
        text-align: center;
        margin: 24px 0 12px 0;
        position: relative;
    }

    img.avatar {
        width: 40%;
        border-radius: 50%;
    }*/

    .container {
        padding: 16px;
        width: 500px;
    }

    span.psw {
        float: right;
        padding-top: 16px;
    }

    /* The Modal (background) */
    .modal {
        display: none; /* Hidden by default */
        position: fixed; /* Stay in place */
        z-index: 1; /* Sit on top */
        left: 100px;
        top: 50px;
        width: 100%; /* Full width */
        height: 100%; /* Full height */
        overflow: auto; /* Enable scroll if needed */
        background-color: rgb(0,0,0); /* Fallback color */
        background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
        padding-top: 60px;
    }

    /* Modal Content/Box */
    .modal-content {
        background-color: #fefefe;
        margin: 5% auto 15% auto; /* 5% from the top, 15% from the bottom and centered */
        border: 1px solid #888;
        width: 80%; /* Could be more or less, depending on screen size */
    }

    /* The Close Button (x) */
    .close {
        position: absolute;
        right: 25px;
        top: 0;
        color: #000;
        font-size: 35px;
        font-weight: bold;
    }

        .close:hover,
        .close:focus {
            color: red;
            cursor: pointer;
        }

    /* Add Zoom Animation */
    .animate {
        -webkit-animation: animatezoom 0.6s;
        animation: animatezoom 0.6s;
    }
</style>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6" style="background-color:lavender;">
                <h2>Add New Category Diseases</h2>

                <button onclick="document.getElementById('id01').style.display='block'" style="width:auto;">ADD</button>
            </div>
            <div class="col-sm-6" style="background-color:lavender;">
                <h2>Delete Category Diseases</h2>
                <input type="button" class="btn-danger" style="width:70px;height:50px;display:block" value="Delete" onclick="location.href='@Url.Action("Index", "CategoryDiseases") '" />
            </div>
        </div>
    </div>
    <div id="id01" class="modal">


        @using (Html.BeginForm("create", "CategoryDiseases"))
            {
            @Html.AntiForgeryToken()

            @*<div class="imgcontainer">
                    <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">&times;</span>
                    <img src="img_avatar2.png" alt="Avatar" class="avatar">
                </div>*@

            <div class="container">
                <label><b>Category Disease</b></label>
                <input type="text" placeholder="Enter Category Disease Name" name="CategoryName" required>

                @*<label><b>Password</b></label>
                        <input type="password" placeholder="Enter Password" name="psw" required>


                        <input type="checkbox" checked="checked"> Remember me
                    </div>*@
                <button type="submit">Add</button>
                @*<div class="container" style="background-color:#f1f1f1">
                        <button type="button" onclick="document.getElementById('id01').style.display='none'" class="cancelbtn">Cancel</button>
                        <span class="psw">Forgot <a href="#">password?</a></span>
                    </div>*@
            </div>
        }
    </div>

    <script>
        // Get the modal
        var modal = document.getElementById('id01');

        // When the user clicks anywhere outside of the modal, close it
        window.onclick = function (event) {
            if (event.target == modal) {
                modal.style.display = "none";
            }
        }
    </script>

</body>

PharmacySystem/AdminLTE Template1/Views/Medicines/DateExpaired.cshtml
@model IEnumerable<AdminLTE_Template1.Models.MedicineDetail>
<link rel="stylesheet" href="~/Content/css/bootstrap.css" />
<h3 style="color:crimson;text-align:center"><b><u>Expired Medicine Details</u></b></h3>
<br />
<script src="https://cdn.datatables.net/responsive/2.1.1/js/responsive.bootstrap.min.js"></script>
@if (Model.Count() == 0)
{
    <h3 style="color:red">Expired Medicines Are Not in database</h3>
}
else
{
<table class="table">
    <tr class="bg-primary">
        <th>
            @Html.DisplayNameFor(model => model.MedicineName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ManufacturedDate)
        </th>
        <th>
            @Html.DisplayName("ExpiredDate(mm/dd/yyyy)")
        </th>
        
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        
        <th>
            @Html.DisplayNameFor(model => model.CategoryDisease.CategoryName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model)
{
    <tr class="bg-danger" style="font-size:medium">
        <td>
            @Html.DisplayFor(modelItem => item.MedicineName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ManufacturedDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ExpiredDate)
        </td>
        
        <td>
            <img src="~/Content/img/@item.Image" width="90" height="90" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
       
        <td>
            @Html.DisplayFor(modelItem => item.Quantity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CategoryDisease.CategoryName)
        </td>
        <td>
            <div class="btn btn-info">@Html.ActionLink("Details", "Details", new { id = item.M_ID })</div> |
            <div class="btn btn-info">@Html.ActionLink("Delete", "Delete", new { id = item.M_ID })</div> 
</td>
    </tr>
}

</table>
}

PharmacySystem/AdminLTE Template1/Views/Medicines/DateToBeExpaired.cshtml
@model IEnumerable<AdminLTE_Template1.Models.MedicineDetail>

<h3 style="color:crimson;text-align:center"><b><u>Medicines Details Which Expire Within Next 30 Days</u></b></h3>
<br />

<table class="table">
    <tr class="bg-primary">
        <th>
            @Html.DisplayNameFor(model => model.MedicineName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ManufacturedDate)
        </th>
        <th>
            @Html.DisplayName("ExpiredDate(mm/dd/yyyy)")
        </th>
        
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
      
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CategoryDisease.CategoryName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr style="font-size:medium" class="success">
        <td>
            @Html.DisplayFor(modelItem => item.MedicineName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ManufacturedDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ExpiredDate)
        </td>
       
        <td>
            <img src="~/Content/img/@item.Image" width="90" height="90" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
       
        <td>
            @Html.DisplayFor(modelItem => item.Quantity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CategoryDisease.CategoryName)
        </td>
        <td>
            <div class="btn btn-info">@Html.ActionLink("Details", "Details", new { id = item.M_ID })</div> |
            <div class="btn btn-info">@Html.ActionLink("Delete", "Delete", new { id = item.M_ID })</div>
</td>
    </tr>
}

</table>

PharmacySystem/AdminLTE Template1/Views/Medicines/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<AdminLTE_Template1.Models.MedicineDetail>
@*@{
        Layout ="~/Views/Shared/_LayoutMedincinesIndex.cshtml" ;
    }*@
<a href="~/Views/Shared/_Header.cshtml"></a>
<link href="~/Content/Site.css" rel="stylesheet" />



<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Medicines </title>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    @*<link rel="stylesheet" href="/resources/demos/style.css">*@
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    @*<script>
            $(function () {
                $("#dialog").dialog(
                    {
                        modal: true,
                        buttons: {
                            Ok: function () {
                                $(this).dialog("close");
                            }
                        }
                    });
            })
        </script>*@
</head>
<body>


</body>
</html>


@using (Html.BeginForm("Index", "Medicines", FormMethod.Get))
{
    <h3> Search Option:</h3>
    @Html.RadioButton("option", "MedicineName", true)
    <text>MedicineName</text>
    @Html.RadioButton("option", "CategoryID")
    <text> CategoryID </text>
    @Html.TextBox("search")
    <input type="submit"
           name="submit"
           value="Search" />
}
@if (Model.Count() == 0)
{
    <h3 style="color:red">Records not found</h3>
    <script type="text/javascript">
        document.write('<a href="' + document.referrer + '">Go Back</a>');
    </script>
}
    @*<h3 style="color:red">@ViewData["ErrorMessage"]</h3>*@
    <h3><em>Medicines</em> Details</h3>
    @foreach (var item in Model)
    {
        if (item.Quantity < 2)
        {
            @*<div id="dialog" title="Quantity is Low">*@
    foreach (var item1 in Model)
    {
     
        if (item1.Quantity < 2)
        {
           
                        <div id="boxes">
                            <div id="dialog" class="window">
                                Your Content Goes Here<button i="close" class="ui-dialog-close">&#215;</button>
                                <h3>Your Account Is blocked</h3>
                                <a href="@Url.Action("index", "Home")">@item1.MedicineName</a><br />
                                @item1.Quantity
                                <div id="popupfoot">
                                    <a href="#" class="close agree">I agree</a> | <a class="agree" style="color:red;" href="#">I do not agree</a>
                                </div>
                            </div>
                            <div id="mask"></div>
                        </div>



        }

    }
            @*</div>*@
        }
        <div class="genre">
            <ul id="Medicine_View">

                <li>
                    <a href="@Url.Action("Details", new { id = item.M_ID })">
                        <img alt="@item.MedicineName" src="~/Content/img/@item.Image" width="100" height="100" />
                        <span>@item.MedicineName</span>
                    </a>
                </li>

            </ul>
        </div>
    }
    <div class="row">
        <div class="col-sm-12">

            <div style="text-align:left">
                @Html.PagedListPager(Model, pageNumber => Url.Action("Index", new
       {
           pageNumber,
           option = Request.QueryString["option"],
           search = Request.QueryString["search"]
       }))
            </div>
        </div>


    </div>
    <div class="row">
        <div class="col-lg-6">
            <input type="button" class="btn-danger" style="width:100%;height:50px;display:block" value="Account" onclick="location.href='@Url.Action("Index", "CreatePDF") '" />
        </div>
        @*<div class="col-lg-6">
            <input type="button" class="btn-danger" style="width:100%;height:50px;display:block" value="High chart" onclick="location.href='@Url.Action("CharterColumn", "CreatePDF") '" />
        </div>*@
    </div>
    <style>
        #mask {
            position: absolute;
            left: 0;
            top: 0;
            z-index: 9000;
            background-color: #000;
            display: none;
        }

        #boxes .window {
            position: absolute;
            left: 0;
            top: 0;
            width: 440px;
            height: 500px;
            display: none;
            z-index: 9999;
            padding: 20px;
            border-radius: 15px;
            text-align: center;
        }

        #boxes #dialog {
            width: 450px;
            height: 500px;
            padding: 10px;
            background-color: #ffffff;
            font-family: 'Segoe UI Light', sans-serif;
            font-size: 15pt;
        }

        #popupfoot {
            font-size: 16pt;
            position: absolute;
            bottom: 0px;
            width: 250px;
            left: 70px;
        }
    </style>
    <script>
        $(document).ready(function () {


            var id = '#dialog';

            //Get the screen height and width
            var maskHeight = $(document).height();
            var maskWidth = $(window).width();

            //Set heigth and width to mask to fill up the whole screen
            $('#mask').css({ 'width': maskWidth, 'height': maskHeight });

            //transition effect
            $('#mask').fadeIn(500);
            $('#mask').fadeTo("slow", 0.9);

            //Get the window height and width
            var winH = $(window).height();
            var winW = $(window).width();

            //Set the popup window to center
            $(id).css('top', winH / 2 - $(id).height() / 2);
            $(id).css('left', winW / 2 - $(id).width() / 2);

            //transition effect
            $(id).fadeIn(2000);

            //if close button is clicked
            $('.window .close').click(function (e) {
                //Cancel the link behavior
                e.preventDefault();

                $('#mask').hide();
                $('.window').hide();
            });
            $('.ui-dialog-close').click(function (e) {
                e.preventDefault();
                $('#mask').hide();
                $('.window').hide();
            });

            //if mask is clicked
            $('#mask').click(function () {
                $(this).hide();
                $('.window').hide();
            });
        }
        )
    </script>